### PR TITLE
[feat] progress dots

### PR DESCRIPTION
**Pull request by sempsmahad**
### Description
- In response to issue #16 progress indicators (dots) have been added

### Changes
- kotlinized the present dormant java method to create the dots

### CODE REVIEW

**Comment by DoozyDoz** [comment]
Thanks for the work @sempsmahad , the dots appear and actually tell the progress which addresses the issue, however the app crushes when I scroll through the cards (towards the end) Kindly address this before I merge

**Comment by sempsmahad** [comment]
Just noticed , looks like an `index out of bounds`.
Let push a fix

**Comment by sempsmahad** [comment]
@DoozyDoz Updated and tested on my Xiaomi no longer crushes

**Comment by DoozyDoz** [comment]
This is basing on the assumption that the questions are never less or more than 8 ?
looks like a hack , but will do for now

**Pull request merged**
