### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Anzo52**
Need to flesh it out a bit but it's a start.

### CODE REVIEW

**Comment by DoozyDoz** [comment]
@Anzo52  thanks for the contribution, its a step 👌👌👌

**Comment by Anzo52** [comment]
I don't do android stuff very often because my gateway goes catatonic whenever I run Studio. But I'll try and play around with this a bit and try and document more of the functionality. I feel like I'm behind in my best-practices/documentation knowledge (I'm self-taught), so any advice or criticism is appreciated! 👍

**Comment by DoozyDoz** [comment]
Sounds good @Anzo52 , nice to have you on board

**Comment by DoozyDoz** [comment]
addressed issue #5

**Pull request merged**
