### PR TITLE
Feat/qtn card enhancements

### PR DESCRIPTION
**Pull request by sempsmahad**
### Description
- in response to bullet one of issue #30 

### Changes
- added answer view
- removed zoom controls
- toggle answer visibility functionality

### CODE REVIEW

**Comment by DoozyDoz** [comment]
Let me run and revert shortly

**Comment by DoozyDoz** [comment]
This looks good 
<p float="left">
  
   
</p>

Looks like you used a single image as the hidden answer , what happened to the blurring library I saw you use in one of the commits?

**Comment by sempsmahad** [comment]
Thanks @DoozyDoz The first custom view had a great impact on performance the blurred overlay kept on being recreated and rerendered all the time,
[wasabeef's library](https://github.com/wasabeef/Blurry) was the better option but it demanded an Imageview in place for our Mathview (webview) I kept getting errors. Till I resolved to use the hack.

**Comment by DoozyDoz** [comment]
Wow must have been a roller-coaster.
The hack is fine for now, performance wise too. We shall find a better approach later.

**Pull request merged**
